{{- if eq .Values.env.CREATE_ADMIN "1" }}
{{- $secretName := printf "%s-admin" (include "miniflux.fullname" .) }}
{{- if not (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- $rootPasswordValue := (randAlpha 16) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miniflux.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  username: {{ printf "admin" | b64enc }}
  password: {{ $rootPasswordValue | b64enc }}
{{- end -}}
{{- end }}
