env:
  HELM_VERSION: v3.13.3

name: CD
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: publish gcr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout repo
      
      - name: install helm
        uses: Azure/setup-helm@v3
        with:
          # Version of helm
          version: ${{ env.HELM_VERSION }}
        id: install
      - name: Push Helm chart to OCI compatible registry (Github)
        uses: bsord/helm-push@4.1.0
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/${{ github.repository }}
          username: lewis262626
          access-token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
          force: true
          chart-folder: .

