env:
  HELM_VERSION: v3.13.3

name: CD
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: publish gcr
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        name: checkout repo
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Push | OCI
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: miniflux
          repository: ${{ github.repository }}
          tag: ${{ env.RELEASE_VERSION }}
          path: .
          registry: ghcr.io
          registry: ${{ env.REGISTRY }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
